import os

DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_PASSWORD = os.getenv('DATABASE_PASSWORD')
DATABASE_HOST = os.getenv('DATABASE_HOST')
DATABASE_PORT = os.getenv('DATABASE_PORT')
DATABASE_NAME = os.getenv('DATABASE_NAME')
DATABASE_CONNECTION_URL = f"mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"

GLOBOMAIL_DB_USER = os.getenv('GLOBOMAIL_DB_USER')
GLOBOMAIL_DB_PASSWORD = os.getenv('GLOBOMAIL_DB_PASSWORD')
GLOBOMAIL_DB_HOST = os.getenv('GLOBOMAIL_DB_HOST')
GLOBOMAIL_DB_NAME = os.getenv('GLOBOMAIL_DB_NAME')

AUTH_USER = os.getenv('AUTH_USER')
AUTH_PASSWORD = os.getenv('AUTH_PASSWORD')
AUTH_URL = os.getenv('AUTH_URL')
AUTH_SERVICE_BLUEBIRD = os.getenv('AUTH_SERVICE_BLUEBIRD')

BLUEBIRD_URL = os.getenv('BLUEBIRD_URL')

PAYMENT_TIMEOUT = os.getenv('PAYMENT_TIMEOUT')
CART_TIMEOUT = os.getenv('CART_TIMEOUT')
CHECKOUT_TIMEOUT = os.getenv('CHECKOUT_TIMEOUT')
AUTH_TIMEOUT = os.getenv('AUTH_TIMEOUT')
DATABASE_CONNECTION_TIMEOUT = os.getenv('DATABASE_CONNECTION_TIMEOUT')